image: harbor1.zitcom.dk/onpay/php82:latest

stages:
  - test

before_script:
  - COMPOSER_MEMORY_LIMIT=-1 composer install --no-interaction --no-progress

phpunit:
  stage: test
  artifacts:
    reports:
      junit: phpunit-report.xml
  script:
    - php ./vendor/phpunit/phpunit/phpunit --log-junit phpunit-report.xml --testsuite All
